### ISSUE TITLE
Ficar Pin Mi4W

### ISSUE THREAD

**Issue by lavinski7** [deivids84/MA-XML-7.0-CATALAN#37]
Al ficar el pin en el meu Mi4 hi ha un error, no posa pin i es confon amb eliminar i l'últim dígit a clicar sembla com si no aparegués

Gràcies i bona feina!

**Comment by ingbrzy** [comment]
post screenshots and which MIUI version.. thx

**Comment by lavinski7** [comment]
Sorry ingbrzy, i have an Mi4W, Mui version  6.10.27 from xiaomi.eu

I add two screenshots and you can check this issue, first i cant read 'PIN'
or 'Introdueix PIN' and then i can check my last number.

Thanks

El dia 29 oct. 2016 18:47, "ingbrzy" notifications@github.com va escriure:

**Comment by ingbrzy** [comment]
where are screenshots?

**Comment by lavinski7** [comment]
Last email...you cant see it??
Like attached file

El dia 29 oct. 2016 20:09, "ingbrzy" notifications@github.com va escriure:

**Comment by ingbrzy** [comment]
https://github.com/deivids84/MA-XML-8.0-CATALAN/issues/37

**Comment by lavinski7** [comment]
![screenshot_2016-10-29-18-52-30-329_lockscreen](https://cloud.githubusercontent.com/assets/23140359/19831896/8f57f726-9e15-11e6-9203-a829a8e74979.png)
![screenshot_2016-10-29-18-52-20-742_lockscreen](https://cloud.githubusercontent.com/assets/23140359/19831897/961b0652-9e15-11e6-8f5f-775ce478648e.png)

**Comment by lavinski7** [comment]
Now you can check it sorry

**Comment by lavinski7** [comment]
You can check it now in github, sorry is my first time ;)

Lavinski

El dia 29 oct. 2016 20:23, "ingbrzy" notifications@github.com va escriure:

**Comment by leixet** [comment]
Sí, ens hem adonat d'això i hem corregit la traducció per la pròxima rom setmanal (farem un commit aviat amb aquest i altres canvis). De tota manera, el problema real no és només la cadena "unlock". També la que diu "Enter PIN" que hem traduït per "Introduïu el PIN": el dispositiu mostra només els primers 4 caràcters d'aquesta cadena, resultant en "Intr". Restaurarem la traducció anterior d'aquesta cadena, que era "PIN?". Igualment, gràcies per avisar d'aquest problema @lavinski7 .

Personalment a mi també em passa, però introduïnt el PIN com sempre em funciona (encara q només mostri 3 punts, s'han introduït tots els dígits del PIN correctament). És lamentable, sí, disculpes per l'error en la traducció.

Yes, we've noticed that and corrected translation for next weekly rom (we will push a commit soon with this and other changes). By the way, the real problem is not only the "unlock" string, @ingbrzy . It's also the one that says "Enter PIN" that we translated into "Introduïu el PIN": the device only shows first 4 characters of this string, resulting in "Intr". We will restore this string to previous translation, that was "PIN?". Thanks for let us know this issue @lavinski7 

Personally I was having the same issue, but entering the PIN as usual, it works for me (although it's only showing 3 dots, the other digits of the PIN are correctly entered). It's totally disappointing, I know. Sorry for the mistake in the translation.

**Comment by lavinski7** [comment]
Moltes gràcies i bona feina, i sobretot en cap cas un error lamentable, us
agraeixo enormement poder tenir el mòbil en Català.

De veritat no us imagineu quina satisfacció poder tenir Miui en Català!!

Salut

El dia 30 oct. 2016 00:34, "leixet" notifications@github.com va escriure:
